import numpy as np
import os
import h5py
import time
import cv2
import torch

##### Generated by ChatGPT
def torch_to_cv2_image(torch_image):
    # Step 1: Convert torch tensor to numpy array
    np_image = torch_image.permute(1, 2, 0).cpu().numpy().astype(np.uint8)  # Change [C, H, W] to [H, W, C]
    
    # Step 3: Convert RGB to BGR
    cv2_image = cv2.cvtColor(np_image, cv2.COLOR_RGB2BGR)
    
    return cv2_image


################################################################################
##### We have adopted the event visualizer from the amazing work of E-RAFT #####
################################################################################
def plot_points_on_background(points_coordinates,
                              background,
                              points_color=[0, 0, 255]):
    """
    Args:
        points_coordinates: array of (y, x) points coordinates
                            of size (number_of_points x 2).
        background: (3 x height x width)
                    gray or color image uint8.
        color: color of points [red, green, blue] uint8.
    """
    if not (len(background.size()) == 3 and background.size(0) == 3):
        raise ValueError('background should be (color x height x width).')
    _, height, width = background.size()
    background_with_points = background.clone()
    y, x = points_coordinates.transpose(0, 1)
    if len(x) > 0 and len(y) > 0: # There can be empty arrays!
        x_min, x_max = x.min(), x.max()
        y_min, y_max = y.min(), y.max()
        if not (x_min >= 0 and y_min >= 0 and x_max < width and y_max < height):
            raise ValueError('points coordinates are outsize of "background" '
                             'boundaries.')
        background_with_points[:, y, x] = torch.Tensor(points_color).type_as(
            background).unsqueeze(-1)
    return background_with_points

################################################################################
##### We have adopted the event visualizer from the amazing work of E-RAFT #####
################################################################################
def events_to_event_image(event_sequence):
    width  = 346
    height = 260
    polarity   = event_sequence[:, 3] == -1.0
    x_negative = event_sequence[~polarity, 0].astype(int)
    y_negative = event_sequence[~polarity, 1].astype(int)
    x_positive = event_sequence[polarity, 0].astype(int)
    y_positive = event_sequence[polarity, 1].astype(int)

    positive_histogram, _, _ = np.histogram2d(
        x_positive,
        y_positive,
        bins=(width, height),
        range=[[0, width], [0, height]])
    negative_histogram, _, _ = np.histogram2d(
        x_negative,
        y_negative,
        bins=(width, height),
        range=[[0, width], [0, height]])

    # Red -> Negative Events
    red = np.transpose((negative_histogram >= positive_histogram) & (negative_histogram != 0))
    # Blue -> Positive Events
    blue = np.transpose(positive_histogram > negative_histogram)
    
    # Create a background image
    background = torch.full((3, height, width), 255).byte()
    
    # Visaulize the events
    points_on_background = plot_points_on_background(
        torch.nonzero(torch.from_numpy(red.astype(np.uint8))), background,
        [255, 0, 0])
    points_on_background = plot_points_on_background(
        torch.nonzero(torch.from_numpy(blue.astype(np.uint8))),
        points_on_background, [0, 0, 255])
    
    # Convert image into opencv format
    points_on_background = torch_to_cv2_image(points_on_background)
    
    # Visualization is ready
    return points_on_background

if __name__ == "__main__":
    # Path to data
    path_to_data = os.path.join("/home/hakito/datasets/event_data", "outdoor_day1_data.hdf5")

    # Load the data
    hdf_file = h5py.File(path_to_data, "r")

    # Check what is inside the data
    print("Top-level groups:", list(hdf_file.keys()))

    # Load grayscale data
    gray_image_data = hdf_file['davis']['left']['image_raw']

    # Load event daata
    events_data = hdf_file['davis']['left']['events']

    # Load event to image indexes
    image_raw_event_inds = hdf_file['davis']['left']['image_raw_event_inds']

    # for idx in range(1,gray_image_data.shape[0]-1):
    for idx in range(3250,3500):
        # Get the grayscale image
        img_frame = gray_image_data[idx]
        
        # Apply histogram equalization
        img_frame = cv2.equalizeHist(img_frame)
    
        img_frame = cv2.cvtColor(img_frame, cv2.COLOR_RGB2BGR)
        
        # Get the related events
        related_events = events_data[image_raw_event_inds[idx-1]:image_raw_event_inds[idx+1],:]

        # Visualize the events
        event_image = events_to_event_image(related_events)
        
        # Concatenate images for a better visualization
        out_img = cv2.hconcat([img_frame, event_image])
        
        # Show the image
        cv2.imshow("out_img", out_img)
        key = cv2.waitKey(1)
        if key == ord("q") or key == ord("Q"):
            break
        cv2.imwrite("ExampleFrames/" + str(idx) + ".png", out_img)

    